#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#Rafael Santos

import subprocess
import argparse

parser = argparse.ArgumentParser(description="Subdomain Recon. Usage: ./dns_scan example.com subdomain_wordlist.txt\n[*.example.com will be scanned]")
parser.add_argument("domain", help="Domain To Scan")
parser.add_argument("wordlist", help="Subdomain Wordlist")
args = parser.parse_args()

domain = args.domain
wordlist = args.wordlist

def exec_comand(comand):
    try:
        cmd = subprocess.Popen(comand, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        out = str(cmd.stdout.read())

        return out

    except Exception as error:
        print("exec_comand " + str(error))
        exit(0)

def bruteforce(subdomains, domain):
    print("[*] Scanning *." + domain + "\n")

    for subdomain in subdomains:
        try:
            comand = "host " + str(subdomain) + "." + domain
            out = str(exec_comand(comand)).replace("b'", "").replace("\\n'", "").replace("\\n", " ").replace("\n", " ") #.replace("\r", "").replace("\n", " ")

            if ("not found:" in out) or (out == "") or (len(out) < 4):
                continue

            print(out)

        except KeyboardInterrupt:
            exit(0)

        except Exception as error:
            print(subdomain + " " + str(error).replace("b'", "").replace("\\n'", "").replace("\r", "").replace("\n", " "))


def readFileAndGenerateWordlist(name):
    try:
        file = open(name, "r")
        data = file.readlines()
        file.close()

        subdomains = []

        for line in data:
            line = line.replace("\n", "").replace("\r", "")

            if len(line) == 0:
                continue

            subdomains.append(line)

        if len(subdomains) > 0:
           return subdomains
        else:
            print("Empty Wordlist.")
            exit(0)

    except Exception as error:
        print("readFileAndGenerateWorlist " + str(error))
        exit(0)


def main():
    try:
        subdomains = readFileAndGenerateWordlist(wordlist)
        bruteforce(subdomains, domain)
    except Exception as error:
        print("main " + str(error))


main()
